" For neovim, remap Esc to exit terminal mode
tnoremap è <C-\><C-n>

" Map à to 0 in normal, visual and movement waiting command mode
map à 0

" Makes moving around tabs more easy
map ² gt
map ~ gT
" ~ is <Shift>-² in AZERTY keyboard, make moving between tabs really easy.

" Map é to ~ in normal, visual and movement waiting command mode
noremap é ~

" Quick toggle between spell and nospell
map µ :set spell!<CR>

" Quick binding to use the macro stored in a
map ù @a

" Set the normal vimrc with only Vim compatible command
source ~/.config/nvim/vimrc
