#!/bin/sh

alias cp='cp -iv'
alias cpf='cp -vf'

alias e='$EDITOR'

alias grep='grep -i --color=auto'

alias l='ls'
alias la='ls -A'
alias ll='ls -lh'
alias ln='ln -vf'
alias ls='ls -NF --color=auto --group-directories-first'

alias mkdir='mkdir -v'
alias mv='mv -vf'

alias p='sudo pacman'

alias pwd='pwd -P'	# Show the physical link instead of the symbolic one
alias rm='rm -v'
alias rmdir='rmdir -v'
alias rmrf='rm -vrf'

alias s='sudo '

alias mount='sudo mount -v'
alias umount='sudo umount -v'

alias x='termite -d "$(pwd)" & disown'

alias ..='cd ..'
alias :q='exit'

alias ¤='cd ~/Doc/dotsfiles'
alias à='cd -'
