# If not running interactively, exit
case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

LESSHISTFILE=/dev/null

PS1="\[\e[38;5;99m\]\u\[\e[0m\]@\[\e[38;5;197m\]\h\[\e[0m\]:[\[\e[38;5;156m\]\W\[\e[0m\]]> "

# autocd      :	Remove the need to type cd
# histappend  : Append to the history file, don't overwrite it
# checkwinsize: Update the values of LINES and COLUMNS.
shopt -s autocd histappend checkwinsize

# Remove the <C-s> shortcut that stop input
# And same with <C-q> shortcut that resume input
stty -ixon -ixoff

for src in $(find $HOME/.config/bash/ -type f)
do
	source $src
done
