#!bin/sh

export PATH=$PATH:.
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

export EDITOR=/usr/bin/nvim
export BROWSER=/usr/bin/firefox

export HISTCONTROL=erasedups
export HISTFILE=$HOME/.config/history
export HISTFILESIZE= 
export HISTSIZE= 


export LESSHISTFILE=/dev/null

export PATH=$PATH:.
